Expand features tested around unzipped bags
artefactual-labs/archivematica-acceptance-tests pull request #148
Opened 2019-10-02 12:51 UTC by ross-spencer

Data in bag transfers also augments the METS that is output in the
AIP. These tests will help generate assurance this data persists
at ingest, and following re-ingest.

Connected to archivematica/issues#914

2019-10-03 16:31 UTC, replaceafill requested changes
This looks OK to me. I just think we should move the helper to the `utils.py` module.

2019-10-03 16:31 UTC, replaceafill commented on features/steps/black_box_steps.py
> +    for i, _ in enumerate(transfer_md[0].iter()):
Would `len(transfer_md[0])` not work here?

2019-10-03 16:31 UTC, replaceafill commented on features/steps/black_box_steps.py
> +def validate_source_md_in_bagit_mets(context, reingested=False):
Could this be converted in a helper function in the `utils.py` module?

2019-10-03 16:31 UTC, replaceafill commented on features/steps/black_box_steps.py
> +    validate_source_md_in_bagit_mets(context, reingested=True)
I think it's good to avoid passing the context to helper functions. It's a bit more work in the step code but it makes the helper more independent.

2019-10-04 13:45 UTC, ross-spencer commented on features/steps/black_box_steps.py
> +    for i, _ in enumerate(transfer_md[0].iter()):
It sure did! Not sure why I missed that! :slightly_smiling_face:

2019-10-04 13:47 UTC, ross-spencer commented
Thanks @replaceafill. I've made those changes. Let me know if you see any improvements I can make to the way I'm passing the args. I'm falling a bit short on ideas on that, but they may be okay.

2019-10-04 15:04 UTC, replaceafill approved these changes
LGTM :+1:

2019-10-06 14:29 UTC, merged